# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'REALM2.0' do

use_frameworks!
pod 'RealmSwift'
pod “MDWamp”
end

target 'REALM2.0Tests' do

end

